site_name: Awesome .Net Core Educations
site_url: https://mehdihadeli.github.io/awesome-dotnet-core-education/
site_description: A curated list of awesome articles and resources for learning and practicing about .Net Core and its related technologies.
docs_dir: docs
repo_name: mehdihadeli/awesome-dotnet-core-education
repo_url: https://github.com/mehdihadeli/awesome-dotnet-core-education
edit_uri: edit/main/docs/
theme: 
  name: material 
  palette:
    primary: 'deep purple'
    accent: 'indigo'  
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - .Net:
    - .Net : dotnet/dotnet.md
    - .Net 5: dotnet/dotnet5.md
    - .Net 6: dotnet/dotnet6.md  
    - .Net Standard: dotnet/dotnet-standard.md
    - ASP.Net Core: dotnet/dotnet-core.md
    - .Net Core Architecture: dotnet/dotnet-core-architecture.md
  - .Net CLI: 
    - .Net CLI: dotnet-cli/dotnet-cli.md
    - .Net Template: dotnet-cli/dotnet-template.md
    - .Net Tools: dotnet-cli/dotnet-tools.md
    - .Net Watch: dotnet-cli/dotnet-watch.md
    - Upgrade Assistant: dotnet-cli/upgrade-assistant.md
  - .Net Core Tips: dotnet/dotnet-core-tips.md
  - .Net IL: dotnet/il.md
  - MetaPack: dotnet/metapack.md
  - C#: 
    - C#: csharp/csharp.md
    - C# Versions:
      - C# 10: csharp/versions/10.md
      - C# 9: csharp/versions/9.md
      - C# 8: csharp/versions/8.md
      - C# 7: csharp/versions/7.md
    - Async: 
      - Async And Await: csharp/async/async-and-await.md
      - Async Best Practice: csharp/async/async-best-practice.md
      - Async Collections: 
        - Async Collections: csharp/async/async-collections.md
        - Async Stream And IEnumerableAsync: csharp/async/async-collections/async-stream-and-ienumerableasync.md
        - Blocking Collection: csharp/async/async-collections/blocking-collection.md
        - Iterators: csharp/async/async-collections/iterators.md
        - Lazy Initialization: csharp/async/async-collections/lazy-initialization.md
      - Asynchronous Messaging: csharp/async/asynchronous-messaging.md
      - Async Local: csharp/async/asynclocal.md
      - Awaiter: csharp/async/awaiter.md
      - Cancellation: csharp/async/cancellation.md
      - Channels: csharp/async/channels.md
      - Concurrency Vs Parallelism: csharp/async/concurrency-vs-parallelism)
      - Configure Await: csharp/async/configure-await.md
      - Continuations.md: csharp/async/continuations.md
      - Cpu Bound: csharp/async/cpu-bound.md
      - Exception Handling: csharp/async/exception-handling)
      - Io Bound: csharp/async/io-bound.md
      - Synchronization Context: csharp/async/synchronization-context.md
      - State Machine: csharp/async/state-machine.md
      - TaskCompletionSource: csharp/async/task-completion-source.md
      - TPL & TAP: csharp/async/tpl-tap.md
      - ThreadPool: csharp/async/thread-pool.md
      - Thread Safty: csharp/async/thread-safty.md
      - Thread: csharp/async/thread.md
      - ValueTask: csharp/async/valuetask.md
      - Sync Over Async: csharp/async/sync-over-async.md
      - Resources: csharp/async/resources.md
    - Collections & Data Structure:
      - Collections & Data Structure: csharp/collections/collection-data-structure.md
      - Enumerable: csharp/collections/enumerable.md
      - HashSet: csharp/collections/hashset.md
    - Boxing: csharp/boxing.md
    - Closure: csharp/closure.md
    - Constant: csharp/constant.md
    - Operator: csharp/implicit-explicit-operators.md
    - Linq: csharp/linq.md
    - Lowering: lowering.md
    - Extension Methods: csharp/extension-methods.md
    - Null Checking : csharp/null-check.md
    - Reflection : csharp/reflection.md
    - Generic: csharp/generic.md
    - Types : csharp/types.md
    - Span: csharp/span.md
    - Record: csharp/record.md
    - Enum: csharp/enum.md
  - Code Coverage & Analysis: code-coverage-analysis.md
  - MAUI: maui.md
  - Blazor: blazor.md
  - API Documentation: api-documentation.md
  - Source Generators: source-generators.md
  - Performance: performance.md
  - Health Check: health-check.md
  - Serialization: serialization.md
  - Generic Host And Web Host: generic-host.md
  - Hosting: hosting.md
  - Kestrel: kestrel.md
  - Feature Flags: feature-flags.md
  - REST: rest.md
  - Middleware: middleware.md
  - Action Filters: action-filters.md
  - Configuration: configuration.md
  - Options: options.md
  - HttContext && HttpContextAccessor: httpcontext.md
  - gRPC: grpc.md
  - WebSockets: web-sockets.md
  - SignalR: signalr.md
  - HttpClient: httpclient.md
  - WEB API: web-api.md
  - Minimal API: minimal-api.md
  - ML.Net : ml-net.md
  - Background Tasks: background-tasks.md
  - Validation: validation.md
  - Razor Pages: razor-pages.md
  - GraphQL: graphql.md
  - NoSQL: 
    - NoSQL: nosql/nosql.md
    - CosmosDB: nosql/cosmosdb.md
    - PostgreSQL: nosql/postgresql.md
    - MongoDB: nosql/mongodb.md
    - RavenDB: nosql/ravendb.md
  - Docker: docker.md
  - Git: git.md
  - Git-Flow: git-flow.md
  - Elastic Search: elastic-search.md
  - OData: odata.md
  - Debugging: debugging.md
  - Nuget: nuget.md
  - API Versioning: api-versioning.md
  - Hosted Service: hosted-service.md
  - Routing: routing.md
  - Dependency Injection: dependency-injection.md
  - Security: 
    - Encryption And Data Protection: security/encryption.md
    - .Net Core Identity: security/dotnet-identity.md
    - Identity Server: security/identity-server.md
    - MSAL: security/msal.md
    - Authentication: security/authentication.md
    - Authorization: security/authorization.md
    - OAuth & OpenID Connect: security/oauth-opencid.md
    - Refresh Token: security/refresh-token.md
    - Secret Management: security/secret-management.md
  - Logging And Auditing: logging.md
  - Distributed Tracing: distributed-tracing.md
  - Diagnostics: diagnostics.md
  - Testing: 
    - Testing: testing/testing.md
    - Unit Testing: testing/unit-testing.md
    - Integration Testing: testing/integration-testing.md
    - End-To-End Testing: testing/end-to-end-testing.md
    - Acceptance Testing: testing/acceptance-testing.md
    - Load Testing: testing/load-testing.md
    - Architectural Testing: testing/architectural-testing.md
    - Contract Testing: testing/contract-testing.md
    - Test Host And WebApplicationFactory: testing/test-host.md
    - Mocking: testing/mocking.md
    - TDD: testing/tdd.md
    - BDD: testing/bdd.md
    - XUnit: testing/xunit.md
  - Exception Handling: exception-handling.md
  - EF Core: 
    - EF Core: ef-core/ef-core.md
    - EF Core 5: ef-core/ef-core-5.md
    - EF Core 6: ef-core/ef-core-6.md
    - Expression Tree: ef-core/expression-tree.md
    - EF Core Migrations: ef-core/ef-core-migration.md
    - Explicit Loading: ef-core/explicit-loading.md
    - Eager Loading: ef-core/eager-loading.md
    - Lazy Loading: ef-core/lazy-loading.md
    - Performance: ef-core/performance.md
    - Transaction: ef-core/transaction.md
    - Change Tracking: ef-core/change-tracking.md
  - Environment: environment.md
  - Mediator: mediator.md
  - Mapping: mapping.md
  - Caching: caching.md
  - Benchmarking: benchmarking.md
  - Rate Limiting: rate-limiting.md
  - Package Versioning: package-versioning.md
  - Orleans: orleans.md
  - CI/CD: 
    - Azure Devops: ci-cd/azure-devops.md
    - GitHub Actions: ci-cd/github-actions.md
    - Jenkins: ci-cd/jenkins.md
  - Roslyn: roslyn.md
  - IDE & Tools: 
    - Reharper & Rider: ide-tools/resharper-rider.md
    - GitHub: ide-tools/github.md
    - Decompile: ide-tools/decompile.md
    - DotMemory: ide-tools/dotmemory.md
    - Terminal Tools: ide-tools/terminal.md
    - WSL: ide-tools/wsl.md
  - Rx.Net: rx.md
  - Commenting: commenting.md
  - Others: others.md


copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
