site_name: Awesome .Net Core Educations
site_url: https://mehdihadeli.github.io/awesome-dotnet-core-education/
site_description: A curated list of awesome articles and resources for learning and practicing about .Net Core and its related technologies.
docs_dir: docs/
repo_name: 'GitHub'
repo_url: https://github.com/mehdihadeli/awesome-dotnet-core-education
theme: 
  name: material 
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
extra_css:
  - static/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
      #baselevel: 2
nav:
  - .Net:
    - .Net : dotnet/dotnet.md
    - .Net Core: dotnet/dotnet-core.md
    - .Net Standard: dotnet/dotnet-standard.md
    - .Net 5: dotnet/dotnet5.md
    - .Net 6: dotnet/dotnet6.md
  - .Net CLI: 
    - .Net CLI: dotnet/dotnet-cli.md
    - .Net Template: dotnet/dotnet-template.md
  - .Net Tools: dotnet/dotnet-tools.md
  - .Net Core Tips: dotnet/dotnet-core-tips.md
  - MetaPack: dotnet/metapack.md
  - C#:
    - C# 7: c#/c#7.md
    - C# 8: c#/c#8.md
    - C# 9: c#/c#9.md



copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli